include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    unused_local_variable: error
    unused_import: error

linter:
  rules:
    always_declare_return_types: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    prefer_final_locals: true
    prefer_single_quotes: true
    use_super_parameters: true
